### ISSUE TITLE
Extracting basic Aadhaar information

### ISSUE THREAD

**Issue by aguzmant103** [anon-aadhaar/anon-aadhaar#131]
Possible solutions:
- Dynamic Array Extraction (most promising): the index of each value could be different for each user. We need to know each step for several values. Some value acts (#) as the delimiter. 
- ZK-Regex (maybe not needed)

Goal of extracting fields:
- Name
- Aadhaar Number
- Date of Birth

Nullifier in #132

**Comment by Meyanis95** [comment]
Merged on #139
