### ISSUE TITLE
Derive nullifier from data in aadhaar QR

### ISSUE THREAD

**Issue by aguzmant103** [anon-aadhaar/anon-aadhaar#132]
Depends on #131 

Nullifier:
- hash(LAST 4 DIGITS + NAME + DATE OF BIRTH)

Considerations:
- Collision risk:
- Double spending:
- Changing NAME or DATE OF BIRTH:

Nullifier targets:
- Max lifetime: 2 weeks?

**Comment by vuvoth** [comment]
The function hash(LAST 4 DIGITS + NAME + DATE OF BIRTH) have the collision risk.

**Comment by vuvoth** [comment]
Resolve in #139
