### ISSUE TITLE
Extracting timestamp Aadhaar

### ISSUE THREAD

**Issue by aguzmant103** [anon-aadhaar/anon-aadhaar#134]
Similar to the work done on #131 
- Timestamp: (this enables further security on the application layer)

Ideal Format: UNIX timestamp
Current Format:
- referenceID - last 4 digits of Aadhaar code and data time stamp in "DDMMYYYYHHMMSSsss" (including milliseconds)

**Comment by Meyanis95** [comment]
Merged on #143
