### ISSUE TITLE
v1.0.0 Trusted Setup Ceremony

### ISSUE THREAD

**Issue by aguzmant103** [anon-aadhaar/anon-aadhaar#135]
ETA: first week of sprint 2
~ Jan 15-22nd

**Comment by aguzmant103** [comment]
Create a configFile.json following this guide: https://github.com/privacy-scaling-explorations/DefinitelySetup/tree/main/ceremonies#template-in-details 

Please help us know if you need any guidance or you have any questions 😊 

Check an example file in the conversation: https://discord.com/channels/943612659163602974/948826990960607262/1192172977568088184

**Comment by Meyanis95** [comment]
Done
