### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by 0xmihirsahu** [anon-aadhaar/anon-aadhaar#218]
# What is the bug? 

![image](https://github.com/anon-aadhaar/anon-aadhaar/assets/114948140/864ff03f-7b68-4db5-83c7-a0938de64b6a)
There a typo in documentation. "indetity" should be "identity".

# How can it be reproduced?

https://documentation.anon-aadhaar.pse.dev/docs/how-does-it-work#rsa-and-document-verification

in the last line there's a typo

**Comment by saleel** [comment]
Fixed, thank you.
