### ISSUE TITLE
One time/limited use pcd argument. 

### ISSUE THREAD

**Issue by vuvoth** [anon-aadhaar/anon-aadhaar#59]
Relate with #28 
# Motivation
We can limited number proof user can create. This is useful for avoid spam and DOS attack 

# Research 
We can add RLN circuit to our circuit or think about another solution.

**Comment by aguzmant103** [comment]
RLN is a good one, we could also add an "expiration time" similar to how Semaphore implementes "fingerprint duration"

**Comment by vuvoth** [comment]
Yes, this is the first solution I think about. We should add this feature to Anon Aadhaar v2.

**Comment by Meyanis95** [comment]
This mechanism is not relevant since the new implementation in v1.0.0.
Replaced by signature timestamp as TOTP in https://github.com/anon-aadhaar/anon-aadhaar/pull/143
