### ISSUE TITLE
Recover or disable(Updateble) ID card

### ISSUE THREAD

**Issue by vuvoth** [anon-aadhaar/anon-aadhaar#60]
# What is the bug? 
How we can recover or disable ID card if we lost it? 

# Research 
...

**Comment by aguzmant103** [comment]
@vuvoth what's the current lost & replace process for Aadhaar cards?   Can we leverage that?

**Comment by vuvoth** [comment]
We don't have any process on this problem. I just focus to improve argument system right now. I think should be good if we can add this feature into Anon Aadhaar v2.

**Comment by Meyanis95** [comment]
This mechanism is not relevant since the new implementation in v1.0.0.
Replaced by signature timestamp as TOTP in https://github.com/anon-aadhaar/anon-aadhaar/pull/143
