### ISSUE TITLE
Prove proof not created by user functionability   

### ISSUE THREAD

**Issue by vuvoth** [anon-aadhaar/anon-aadhaar#72]
# Motivation 
We should support selective disclosure on anon aadhaar. Users/Prover can prove they don't create exist proof, without review her/his(their) all information of him. However, Users/Prover can do it if they hold some private information. Malicious parties can not create this proof because they don't know this information. 

We can use this to handle a lot of illegitimate action/transaction. 
# Solution
Researching...

**Comment by Meyanis95** [comment]
This mechanism is not relevant since the new implementation in v1.0.0. 
Replaced by signature timestamp as TOTP in #143
