### ISSUE TITLE
Explore new Aadhaar endpoints

### ISSUE THREAD

**Issue by Meyanis95** [anon-aadhaar/anon-aadhaar#79]
# What is the bug? 
It seems that the Aadhaar pdf cars is not the main way to handle the Indian citizenship. We need to explore new ways to interact with the Indian Identity that feets more with the actual user journey.

**Comment by 0xVikasRushi** [comment]
Hi @vuvoth @Meyanis95.

Aadhaar QR Code contains alot of embedded information. We can decode personal information from qr code and some folks have already done. This is might help in proving custom facts and could be top notch improvement package. I'm very much interested in helping and contribute.

**Comment by 0xVikasRushi** [comment]
And offical [api reference](https://uidai.gov.in/images/resource/User_manulal_QR_Code_15032019.pdf) to decrypt info from qr

**Comment by Meyanis95** [comment]
Delivered on v1.0.0
