### ISSUE TITLE
feat: React Native Support

### ISSUE THREAD

**Issue by 0xVikasRushi** [anon-aadhaar/anon-aadhaar#96]
# Feature
 
Currently `anon-aadhaar-react `  doesn't support with react-native. I'm happy to work package for **anon-aadhaar-react-native**

# Error 

![image](https://github.com/privacy-scaling-explorations/anon-aadhaar/assets/88543171/b45cffa2-7087-4ad9-bd5c-3d1df5d58667)

**Comment by Meyanis95** [comment]
Linked to #140
